# on:
#   pull_request:
#     branches:
#       - main
#       - master
#   push:
#     branches:
#       - main
#       - master
#       - develop

# name: "Build & Release"

# jobs:
#   build:
#     name: Build & Release
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Node.js 20
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Set up Java
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: '12'
#           cache: gradle

#       - name: Set up Cache
#         uses: actions/cache@v3
#         with:
#           path: |
#             ~/.gradle/caches
#             ~/.pub-cache
#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/pubspec.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-gradle-

#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#           architecture: x64
#           cache: true

#       - name: Get dependencies
#         run: flutter pub get
        
#       - run: flutter build appbundle
#       - run: flutter build apk --release --split-per-abi

#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/release/*"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{ secrets.TOKEN }}

# # push to master, main, develop
# # pull request on main master